name: Unit Test Removed Checker
on:
  pull_request:
    branches: [master]

jobs:
  changed_files:
    runs-on: [self-hosted, runner-1]
    outputs:
      modified_test_files: ${{ steps.changes.outputs.modified_test_files }}
      deleted_test_files: ${{ steps.changes.outputs.deleted_test_files }}
    steps:
      - name: Checkout PR Branch
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Get changed files
        id: changes
        # Set outputs using the command.
        run: |
          echo "::set-output name=modified_test_files::$(git diff --name-only --diff-filter=MR ${{ github.event.pull_request.base.sha }} ${{ github.sha }} | grep _test.go$ | xargs)"
          echo "::set-output name=deleted_test_files::$(git diff --name-only --diff-filter=D ${{ github.event.pull_request.base.sha }} ${{ github.sha }} | grep _test.go$ | xargs)
      - name: echo modified with skip
        id: modified_with_skip
        run: |
          for file in ${{steps.changes.outputs.modified_test_files}}
          do
            echo $file
            echo $(git diff $file | grep 't.Skip(*')
          done

          echo "done"
