name: Unit Test Removed Checker
on:
  pull_request:
    branches: [master]

jobs:
  changed_files:
    runs-on: [self-hosted, runner-1]
    outputs:
      skipped_files: ${{ steps.changes.outputs.skipped_files }}
      deleted_test_files: ${{ steps.changes.outputs.deleted_test_files }}
    steps:
      - name: Checkout PR Branch
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Get changed files
        id: changes
        # Set outputs using the command.
        run: |
          echo "::set-output name=skipped_files::$(git diff --name-only --diff-filter=MRA ${{ github.event.pull_request.base.sha }} ${{ github.sha }} -G"t.Skip"| grep _test.go$ | xargs)"

      - name: echo skipped files
        run: |
          echo ${{steps.changes.outputs.skipped_files}}

