name: Unit Test Removed Checker
on:
  pull_request:
    branches: [master]

jobs:
  changed_files:
    runs-on: [self-hosted, runner-1]
    outputs:
      modified_test_files: ${{ steps.changes.outputs.modified_test_files }}
      deleted_test_files: ${{ steps.changes.outputs.deleted_test_files }}
      skipped_files: ${{ steps.modified_with_skip.outputs.skipped_files }}
    steps:
      - name: Checkout PR Branch
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Get changed files
        id: changes
        # Set outputs using the command.
        run: |
          echo "::set-output name=modified_test_files::$(git diff --name-only --diff-filter=MRA ${{ github.event.pull_request.base.sha }} ${{ github.sha }} | grep _test.go$ | xargs)"
          echo "::set-output name=deleted_test_files::$(git diff --name-only --diff-filter=D ${{ github.event.pull_request.base.sha }} ${{ github.sha }} | grep _test.go$ | xargs)"

      - name: get skipped modified tests
        id: modified_with_skip
        run: |
          $f = ""
          for file in ${{steps.changes.outputs.modified_test_files}}
          do
            if echo $(git diff ${{ github.event.pull_request.base.sha }} $file | grep 't.Skip'); then
              echo $file
              f += $file + ", "
            fi
          done
          echo "::set-output name=skipped_files::$f"
          echo "done"
        shell: bash

      - name: echo modified with skip test
        run: echo ${{ steps.modified_with_skip.outputs.skipped_files }}
